# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
description: The cake is a lie!
email: johan @ rymdvarel.se
fullname: Johan Wassberg
title: rymdvarel.se
url: "https://rymdvarel.se" # the base hostname & protocol for your site

# Social
github_username:  theseal
mastodon:
 - username: theseal
   instance: mastodon.social
twitter_username: theseal

# Build settings
markdown: kramdown
theme: minima
timezone: Europe/Stockholm
