# Site settings
title: rymdvarel.se
email: johan @ current site
fullname: Johan Carlquist
description: The cake is a lie!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.rymdvarel.se" # the base hostname & protocol for your site
twitter_username: theseal
github_username:  theseal

# Build settings
markdown: kramdown
