# Site settings
baseurl: ""
description: The universe is a pretty big place. If it's just us, seems like an awful waste of space.
email: johan@rymdvarel.se
author: Johan Wassberg
title: rymdvarel.se
url: "https://rymdvarel.se"

# Social
github_username:  theseal
mastodon:
 - username: theseal
   instance: mastodon.social
twitter_username: theseal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
timezone: Europe/Stockholm
theme: minima

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/apple-icon-76x76.png
