# Site settings
baseurl: ""
description: The universe is a pretty big place. If it's just us, seems like an awful waste of space.
author:
  email: johan@rymdvarel.se
  name: Johan Wassberg
title: rymdvarel.se
url: "https://rymdvarel.se"

# Social
github_username:  theseal
mastodon:
 - username: theseal
   instance: mastodon.social
twitter_username: theseal

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/theseal" }
    - { platform: mastodon,  user_url: "https://mastodon.social/@theseal" }

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

timezone: Europe/Stockholm
remote_theme: jekyll/minima@32468f51758b0b37c2b1f423265d4f29db461b27

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/apple-icon-76x76.png
