# Site settings
title: blog.rymdvarel.se
email: johan @ 
fullname: Johan Wassberg
description: The cake is a lie!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.rymdvarel.se" # the base hostname & protocol for your site
twitter_username: theseal
github_username:  theseal

# Build settings
markdown: kramdown

timezone: Europe/Stockholm

include: [".well-known"]
